---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-agent-deployment
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: go-agent
    spec:
      containers:
      - name: agent
        image: duizhang/go-agent:17.12.0
        imagePullPolicy: Always
        env:
        - name: GO_SERVER_URL
          value: "https://172.31.19.41:8154/go"
        volumeMounts:
        - mountPath: "/var/run/docker.sock"
          name: docker-sock
        - mountPath: "/usr/bin/docker"
          name: docker-bin
      volumes:
      - name: docker-sock
        hostPath:
          path: "/var/run/docker.sock"
      - name: docker-bin
        hostPath:
          path: "/usr/bin/docker"

