---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  namespace: "dev"
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: "dev"
  labels:
    name: redis
spec:
  ports:
  - targetPort: 6379
    port: 6379
  selector:
    app: redis


